name: build

on:
  push:
    paths:
      - '**.js'

jobs:
  build:

    name: my job
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        exclude:
          - os: macos-latest
            node-version: 12.x

    steps:
      - name: my first step
        env:
          MY_VAR: Hi There! my name is
          FIRST_NAME: Joseph-Mark
          MIDDLE_NAME: Charles Junior
          LAST_NAME: Triolo
        run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
