name: build

on: push

jobs:
  build:

    name: my job
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps:
      - name: my first step
        env:
          MY_VAR: Hi There! my name is
          FIRST_NAME: Joseph-Mark
          MIDDLE_NAME: Charles Junior
          LAST_NAME: Triolo
        run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
      - name: my second step
        if: success()
        run: echo "The previous has finished successfully"
